"""empty message

Revision ID: 722760d5dda0
Revises: 
Create Date: 2024-01-11 10:59:31.155159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722760d5dda0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
